services:
  comfyui-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8188:8188"
    volumes:
      - ./output:/home/user/app/output
      - ./input:/home/user/app/input
      - ./models:/home/user/app/models
    environment:
      - USE_PERSISTENT_DATA=false
